# Generated by Django 5.2.8 on 2025-11-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('projetista', models.CharField(max_length=100, verbose_name='Projetista')),
                ('tipo_projeto', models.CharField(max_length=100, verbose_name='Tipo de Projeto')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria')),
                ('dc_id', models.CharField(max_length=50, unique=True, verbose_name='DC/ID')),
                ('metragem_cabo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Metragem de Cabo')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Produção',
                'verbose_name_plural': 'Produções',
                'ordering': ['-data'],
            },
        ),
    ]
