# Generated by Django 5.2.8 on 2025-12-10 17:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='TipoProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo de Projeto',
                'verbose_name_plural': 'Tipos de Projetos',
            },
        ),
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('dc_id', models.CharField(max_length=50, verbose_name='DC/ID')),
                ('metragem_cabo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Metragem de Cabo')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('REVISAO', 'Revisão'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('motivo_status', models.CharField(blank=True, help_text='Ex: Motivo da pendência, do cancelamento ou em que etapa está o andamento.', max_length=255, verbose_name='Motivo/Observação do Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Início')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('data_cancelamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Cancelamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.categoria', verbose_name='Categoria')),
                ('projetista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Projetista')),
                ('tipo_projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipoprojeto', verbose_name='Tipo de Projeto')),
            ],
            options={
                'verbose_name': 'Produção',
                'verbose_name_plural': 'Produções',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('REVISAO', 'Revisão'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], max_length=20, verbose_name='Status')),
                ('motivo', models.CharField(blank=True, max_length=255, verbose_name='Motivo/Observação')),
                ('data_alteracao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Alteração')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que alterou')),
                ('producao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='core.producao', verbose_name='Produção')),
            ],
            options={
                'verbose_name': 'Histórico de Status',
                'verbose_name_plural': 'Históricos de Status',
                'ordering': ['-data_alteracao'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('must_change_password', models.BooleanField(default=True, verbose_name='Forçar troca de senha')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Foto de Perfil')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='RegistroExclusao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dc_id', models.CharField(max_length=50, verbose_name='DC/ID')),
                ('projeto_id_original', models.IntegerField(verbose_name='ID Original do Projeto')),
                ('data_projeto', models.DateField(verbose_name='Data do Projeto')),
                ('tipo_projeto', models.CharField(max_length=100, verbose_name='Tipo de Projeto')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria')),
                ('status_final', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('REVISAO', 'Revisão'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], max_length=20, verbose_name='Status Final')),
                ('metragem_cabo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Metragem de Cabo')),
                ('observacoes_originais', models.TextField(blank=True, verbose_name='Observações Originais')),
                ('total_alteracoes_status', models.IntegerField(default=0, verbose_name='Total de Alterações de Status')),
                ('tempo_total_atividade', models.DurationField(blank=True, null=True, verbose_name='Tempo Total de Atividade')),
                ('motivo_exclusao', models.TextField(verbose_name='Motivo da Exclusão')),
                ('data_exclusao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Exclusão')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('projetista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exclusoes_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Projetista')),
                ('usuario_exclusao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exclusoes_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Excluiu')),
            ],
            options={
                'verbose_name': 'Registro de Exclusão',
                'verbose_name_plural': 'Registros de Exclusão',
                'ordering': ['-data_exclusao'],
                'indexes': [models.Index(fields=['dc_id'], name='core_regist_dc_id_25bbf5_idx'), models.Index(fields=['data_exclusao'], name='core_regist_data_ex_6a46a3_idx'), models.Index(fields=['projetista'], name='core_regist_projeti_90412f_idx'), models.Index(fields=['usuario_exclusao'], name='core_regist_usuario_1b4863_idx')],
            },
        ),
    ]
