# Generated by Django 5.2.8 on 2025-11-28 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo de Projeto',
                'verbose_name_plural': 'Tipos de Projetos',
            },
        ),
        migrations.AlterField(
            model_name='producao',
            name='projetista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Projetista'),
        ),
        migrations.AlterField(
            model_name='producao',
            name='tipo_projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipoprojeto', verbose_name='Tipo de Projeto'),
        ),
    ]
