# Generated by Django 5.2.8 on 2025-11-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_categoria_alter_producao_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producao',
            name='motivo_status',
            field=models.CharField(blank=True, help_text='Ex: Motivo da pendência, do cancelamento ou em que etapa está o andamento.', max_length=255, verbose_name='Motivo/Observação do Status'),
        ),
        migrations.AlterField(
            model_name='producao',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('REVISAO', 'Revisão'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status'),
        ),
    ]
